const state={patients:[],view:"dashboard",patientId:null,tab:"overview",search:"",typeFilter:"All",user:null,loading:true};
window.setTrackerTab=function(tab){state.tab=tab;render();};
function info(label,value){return `<div class="field"><label>${escHtml(label)}</label><div class="info">${escHtml(value||"—")}</div></div>`;}
const app=document.getElementById("app"),modal=document.getElementById("modal-root");
const escHtml=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));const escAttr=escHtml;const fmtDate=d=>d?new Date(d+"T00:00:00").toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}):"—";const fmtINR=n=>"₹"+(Number(n)||0).toLocaleString("en-IN");
function get(id=state.patientId){return state.patients.find(x=>x.id===id)}
function save(){return savePatients(state.patients)}
function render(){
 if(state.loading){app.innerHTML=`<div class="card section"><div class="empty"><strong>Loading IVF Tracker…</strong><div>Connecting to the secure database.</div></div></div>`;return}
 if(!state.user){app.innerHTML=loginScreen();return}
 if(state.view==="dashboard")app.innerHTML=dashboard();else{const p=get();if(!p){state.view="dashboard";return render()}app.innerHTML=patientPage(p)}
}
function loginScreen(){return `<div class="auth-wrap"><div class="auth-card"><img src="logo.jpg" class="auth-logo" alt="Altius Hospitals"><h2>Altius IVF & Maternity Tracker</h2><p class="sub">Secure staff sign-in</p><form id="login-form"><div class="field"><label>Email</label><input class="input" id="login-email" type="email" autocomplete="username" required></div><div class="field"><label>Password</label><input class="input" id="login-password" type="password" autocomplete="current-password" required></div><button class="btn btn-primary" style="width:100%;margin-top:10px">Sign In</button><div id="login-error" class="notice" style="display:none;margin-top:10px"></div></form><div class="small" style="margin-top:12px">Staff accounts are managed in Supabase Authentication. Public sign-up is intentionally not included.</div></div></div>`}
async function init(){try{state.user=await getCurrentUser();if(state.user){state.patients=(await loadPatients()).map(normalizeMaternityPatient)} }catch(e){console.error(e);alert(e.message||"Could not connect to Supabase.")}finally{state.loading=false;render()}}
init();

function dashboard(){
 const psAll=state.patients;
 const typePs=state.typeFilter==="All"?psAll:psAll.filter(p=>(p.programType||"IVF")===state.typeFilter);
 const q=state.search.toLowerCase().trim();
 const fs=q?typePs.filter(p=>[p.name,p.uhid,p.doctor,p.contact,p.partner].some(v=>String(v||"").toLowerCase().includes(q))):typePs;
 const active=typePs.filter(p=>currentProgramStage(p)!=="Completed").length,done=typePs.length-active;
 const isMat=state.typeFilter==="Maternity";
 const title=isMat?"Maternity Patient Tracker":state.typeFilter==="IVF"?"IVF Patient Tracker":"IVF & Maternity Patient Tracker";
 const desc=isMat?"Track trimester 1, 2 and 3 investigations, scans and consultations.":state.typeFilter==="IVF"?"Track IVF package utilisation, daily medication, monitoring, procedures and billing.":"Track IVF cycles and maternity trimester care in one dashboard.";
 return `<div class="page-head"><div><h2>${title}</h2><div class="sub">${desc}</div></div><div class="btn-group"><span class="user-chip">${escHtml(state.user?.email||"")}</span><button class="btn btn-secondary" data-action="sign-out">Sign Out</button><button class="btn btn-primary" data-action="add">+ Add Patient</button><button class="btn btn-secondary" data-action="export-tab">Export Data</button></div></div>
 <div class="filter-bar"><span class="filter-label">Patient Type</span>${["All","IVF","Maternity"].map(t=>`<button class="filter-btn ${state.typeFilter===t?"active":""}" data-action="type-filter" data-type="${t}">${t}</button>`).join("")}</div>
 <div class="stats"><div class="stat"><div class="label">${isMat?"Maternity Patients":"Total Patients"}</div><div class="value">${typePs.length}</div></div><div class="stat"><div class="label">Active</div><div class="value">${active}</div></div><div class="stat"><div class="label">Completed</div><div class="value">${done}</div></div><div class="stat"><div class="label">${isMat?"Trimester Tracking":"Package Value"}</div><div class="value">${isMat?typePs.filter(p=>currentTrimester(p)==="Trimester 1").length+" T1":fmtINR(typePs.reduce((s,p)=>s+(Number(p.packagePrice)||0),0))}</div></div><div class="stat"><div class="label">Extra Charges</div><div class="value">${fmtINR(typePs.reduce((s,p)=>s+extraTotal(p),0))}</div></div></div>
 <div class="toolbar"><input class="search" id="search" placeholder="Search patient, UHID, doctor or phone…" value="${escAttr(state.search)}"><button class="btn btn-secondary" data-action="export-summary-csv">CSV</button><button class="btn btn-secondary" data-action="export-summary-xlsx">XLSX</button><button class="btn btn-secondary" data-action="export-all-xlsx">Full XLSX</button></div>
 <div class="card table-scroll">${fs.length?patientsTable(fs):`<div class="empty"><strong>${typePs.length?"No matching patients":"No patients yet"}</strong>${typePs.length?"Try another search or filter.":"Add the first patient to start tracking."}</div>`}</div>
 <div class="footer">Connected to Supabase. Patient Type filter keeps IVF and Maternity workflows separate while using the same patient database.</div>`;
}
function patientsTable(ps){
 return `<table class="table"><thead><tr><th>Patient</th><th>Type</th><th>Doctor</th><th>Stage</th><th>Progress</th><th>Start / LMP</th><th></th></tr></thead><tbody>${ps.map(p=>{
   const s=programStats(p),st=currentProgramStage(p),mat=(p.programType||"IVF")==="Maternity";
   return `<tr><td><div class="name-link" data-action="open" data-id="${p.id}">${escHtml(p.name||"Unnamed")}</div><div class="small">${escHtml(p.uhid||"No UHID")} · ${escHtml(p.contact||"No phone")}</div></td><td><span class="badge ${mat?"maternity-badge":""}">${mat?"Maternity":"IVF"}</span></td><td>${escHtml(p.doctor||"—")}</td><td><span class="badge ${st==="Completed"?"done":""}">${escHtml(st)}</span></td><td><div class="progress"><div class="track"><div class="fill" style="width:${s.pct}%"></div></div><b>${s.pct}%</b></div></td><td>${fmtDate(mat?p.lmp:p.packageStartDate)}</td><td><button class="btn btn-ghost btn-sm" data-action="open" data-id="${p.id}">Open</button></td></tr>`}).join("")}</tbody></table>`;
}
function patientPage(p){
 const isMat=(p.programType||"IVF")==="Maternity";
 const s=programStats(p);
 return `<div class="page-head"><div><button class="btn btn-ghost" data-action="back-dashboard">← All Patients</button><h2 style="margin-top:8px">${escHtml(p.name||"Unnamed Patient")}</h2><div class="sub"><span class="badge ${isMat?"maternity-badge":""}">${isMat?"Maternity":"IVF"}</span> ${escHtml(p.uhid||"No UHID")} · ${escHtml(p.doctor||"No doctor")}</div></div><div class="btn-group"><button class="btn btn-secondary" data-action="edit">Edit Patient</button><button class="btn btn-secondary" data-action="patient-csv">Export CSV</button><button class="btn btn-primary" data-action="patient-xlsx">Export XLSX</button><button class="btn btn-secondary" data-action="sign-out">Sign Out</button></div></div>
 <div class="patient-card"><div class="patient-head"><div class="info-grid">${info("Contact",p.contact)}${info("Partner",p.partner)}${info("Doctor",p.doctor)}${info("Coordinator",p.coordinator)}${isMat?info("LMP",fmtDate(p.lmp)):info("Package Start",fmtDate(p.packageStartDate))}${isMat?info("EDD",fmtDate(p.edd)):info("Package Price",fmtINR(p.packagePrice))}${isMat?info("Gestational Age",gestationalAge(p)?`${gestationalAge(p).weeks}w ${gestationalAge(p).days}d`:"—"):info("Diagnosis",p.diagnosis)}${info("Stage",currentProgramStage(p))}</div><div><div class="count-box"><b>${s.pct}%</b><span>${s.completed}/${s.total} ${isMat?"tests/scans":"programme items"}</span></div></div></div></div>
 ${isMat?maternityStageBar(p):stageBar(p)}
 <div class="tabs">${(isMat?[["maternity-overview","Overview"],["trimester1","Trimester 1"],["trimester2","Trimester 2"],["trimester3","Trimester 3"],["notes","Notes"],["export","Export Data"]]:[["overview","Overview"],["programme","Programme Checklist"],["stimulation","Stimulation"],["monitoring","Monitoring"],["retrieval","Retrieval & Embryology"],["freezing","Freezing"],["fet","FET"],["pregnancy","Pregnancy"],["charges","Charges"],["notes","Notes"],["export","Export Data"]]).map(x=>`<button type="button" class="tab ${state.tab===x[0]?"active":""}" data-tab="${x[0]}" onclick="window.setTrackerTab('${x[0]}'); return false;">${x[1]}</button>`).join("")}</div>
 ${renderTab(p)}<div class="footer">Last updated: ${new Date(p.updatedAt||Date.now()).toLocaleString("en-IN")}</div>`;
}
function stageBar(p){return `<div class="stagebar">${PHASE_TEMPLATE.map((ph,i)=>{const st=phaseStats(p.phases?.[ph.key]||[]),done=st.pct===100,active=state.tab===ph.key;return `${i?`<div class="connector ${phaseStats(p.phases?.[PHASE_TEMPLATE[i-1].key]||[]).pct===100?"done":""}"></div>`:""}<div class="stage ${done?"done":""} ${active?"active":""}" data-action="tab" data-tab="${ph.key}" onclick="window.setTrackerTab('${ph.key}'); return false;"><div class="node">${done?"✓":i+1}</div><span>${ph.short}</span></div>`}).join("")}</div>`}
function maternityStageBar(p){return `<div class="stagebar">${MATERNITY_TRIMESTERS.map((t,i)=>{const st=maternityStats(p,t.key),done=st.pct===100,active=state.tab===t.key;return `${i?`<div class="connector ${maternityStats(p,MATERNITY_TRIMESTERS[i-1].key).pct===100?"done":""}"></div>`:""}<div class="stage ${done?"done":""} ${active?"active":""}" data-action="tab" data-tab="${t.key}" onclick="window.setTrackerTab('${t.key}'); return false;"><div class="node">${done?"✓":i+1}</div><span>${t.short}</span></div>`}).join("")}</div>`}
function renderTab(p){
 if((p.programType||"IVF")==="Maternity"){
   switch(state.tab){
     case"maternity-overview":return maternityOverview(p);
     case"trimester1":case"trimester2":case"trimester3":return maternityTrimester(p,state.tab);
     case"notes":return notes(p);
     case"export":return exportTab(p);
     default:return maternityOverview(p);
   }
 }
 switch(state.tab){case"overview":return overview(p);case"programme":return `<div class="card section">${PHASE_TEMPLATE.map(ph=>phaseChecklist(p,ph.key)).join("")}</div>`;case"stimulation":return dailyMedication(p,"stimulation")+phaseChecklist(p,"stimulation");case"monitoring":return monitoring(p);case"retrieval":return retrieval(p)+phaseChecklist(p,"retrieval");case"freezing":return freezing(p)+phaseChecklist(p,"freezing");case"fet":return dailyMedication(p,"fet")+phaseChecklist(p,"fet");case"pregnancy":return pregnancy(p)+phaseChecklist(p,"pregnancy");case"charges":return charges(p);case"notes":return notes(p);case"export":return exportTab(p);default:return overview(p)}
}
function maternityOverview(p){
 const s=maternityOverallStats(p),g=gestationalAge(p);
 return `<div class="card section">
   <div class="section-head"><div><h3>Pregnancy Care Tracker</h3><div class="meta">Track the investigations and scans recommended across the three pregnancy trimesters.</div></div><div class="count-box"><b>${currentTrimester(p)}</b><span>${g?`${g.weeks} weeks ${g.days} days`:`Add LMP to calculate gestational age`}</span></div></div>
   <div class="count-strip">${MATERNITY_TRIMESTERS.map(t=>{const x=maternityStats(p,t.key);return `<div class="count-box"><b>${x.completed}/${x.total}</b><span>${t.label} completed</span><small style="display:block;margin-top:4px;color:#6b7280">${x.pct}%</small></div>`}).join("")}</div>
   <div class="notice">The maternity source lists the tests/scans included in each trimester. The checklist below uses the named investigations from the supplied reference. Where the source gives a scan count but no name, the item is labelled as an additional/follow-up scan rather than inventing a clinical test.</div>
   <div class="hr"></div>
   <div class="form-grid">${info("LMP",fmtDate(p.lmp))}${info("Estimated Due Date",fmtDate(p.edd))}${info("Current Trimester",currentTrimester(p))}${info("Gestational Age",g?`${g.weeks} weeks ${g.days} days`:"—")}</div>
 </div>`;
}

function maternityTrimester(p,key){
 const t=MATERNITY_TRIMESTERS.find(x=>x.key===key),a=p.maternity?.[key]||[],s=maternityStats(p,key);
 const blood=a.filter(x=>x.type==="Blood Test"),scans=a.filter(x=>x.type==="Scan");
 const row=(x,i,group)=>`<div class="check-row"><div class="check-main"><div class="check-title">${escHtml(x.item)}</div><div class="small">${escHtml(x.included)}</div></div><input type="date" class="input compact" data-maternity="${key}" data-i="${a.indexOf(x)}" data-f="completedDate" value="${escAttr(x.completedDate||"")}" title="Date completed"><select class="select status-select" data-maternity="${key}" data-i="${a.indexOf(x)}" data-f="status">${MATERNITY_STATUS_OPTIONS.map(v=>`<option ${x.status===v?"selected":""}>${v}</option>`).join("")}</select><input class="input notes-input" data-maternity="${key}" data-i="${a.indexOf(x)}" data-f="notes" value="${escAttr(x.notes||"")}" placeholder="Notes"></div>`;
 return `<div class="card section">
   <div class="section-head"><div><h3>${t.label}</h3><div class="meta">${t.weeks} · ${s.completed} of ${s.total} investigations/scans done · ${s.pct}%</div></div><div class="count-box"><b>${s.completed}/${s.total}</b><span>Completed</span></div></div>
   <div class="progress" style="margin:12px 0 18px"><div class="track"><div class="fill" style="width:${s.pct}%"></div></div><b>${s.pct}%</b></div>
   <div class="notice">Use this page as a simple checklist. Mark each test or scan as <b>Done</b> once completed. The date and notes are optional.</div>
   <h4 style="margin:20px 0 8px">Blood Tests (${blood.length})</h4>
   <div class="checklist">${blood.map((x,i)=>row(x,i,"blood")).join("")}</div>
   <h4 style="margin:22px 0 8px">Scans (${scans.length})</h4>
   <div class="checklist">${scans.map((x,i)=>row(x,i,"scan")).join("")}</div>
   ${t.scanNote?`<div class="small" style="margin-top:10px">${escHtml(t.scanNote)}</div>`:""}
 </div>`;
}

function overview(p){return `<div class="card section"><div class="section-head"><div><h3>Cycle Overview</h3><div class="meta">Package procedure tracker based on the supplied IVF package reference.</div></div></div><div class="count-strip">${PHASE_TEMPLATE.map(ph=>{const s=phaseStats(p.phases?.[ph.key]||[]);return `<div class="count-box"><b>${s.pct}%</b><span>${ph.short} · ${s.completed}/${s.total}</span></div>`}).join("")}</div><div class="notice">Package reference: stimulation includes a 15-day medication course, 2 blood draws, 4 average USG scans and stimulation visits; FET includes 2 blood draws, 5 average USG scans and a 5-day Susten course. Extra usage can be logged and billed separately.</div><div class="hr"></div><div class="form-grid"><div class="field"><label>Clinical Diagnosis</label><div class="info">${escHtml(p.diagnosis||"—")}</div></div><div class="field"><label>Blood Group</label><div class="info">${escHtml(p.bloodGroup||"—")}</div></div><div class="field"><label>Emergency Contact</label><div class="info">${escHtml(p.emergencyContact||"—")}</div></div><div class="field wide"><label>Address</label><div class="info">${escHtml(p.address||"—")}</div></div></div></div>`}
function dailyMedication(p,kind){const arr=kind==="stimulation"?p.stimulationMedication:p.fetMedication;const title=kind==="stimulation"?"Stimulation — Day-wise Medication (15 Days)":"FET — Susten Day-wise Medication (5 Days)";return `<div class="card section"><div class="section-head"><div><h3>${title}</h3><div class="meta">Enter the prescribed dose/time; no medical dose is pre-filled by this tool.</div></div>${kind==="stimulation"?`<button class="btn btn-secondary btn-sm" data-action="auto-dates" data-kind="stimulation">Set 15 dates from package start</button>`:""}</div><div class="notice">${kind==="stimulation"?"Reference CSV: Humog + Cetrorelix, 15-day stimulation course.":"Reference CSV: Susten injection course, 5 days before transfer."} Record whether each day was administered and add pharmacy/clinical notes as needed.</div><div class="table-scroll" style="margin-top:12px"><table class="table day-table"><thead><tr><th>Day</th><th>Date</th><th>Medication</th><th>Dose</th><th>Unit</th><th>Time</th><th>Administered</th><th>Status</th><th>Notes</th></tr></thead><tbody>${arr.map((x,i)=>`<tr><td class="day-cell">Day ${x.day}</td><td><input class="input" type="date" data-med="${kind}" data-i="${i}" data-f="date" value="${x.date}"></td><td><input class="input" data-med="${kind}" data-i="${i}" data-f="medication" value="${escAttr(x.medication)}"></td><td><input class="input" data-med="${kind}" data-i="${i}" data-f="dose" value="${escAttr(x.dose)}" placeholder="Prescribed"></td><td><input class="input" data-med="${kind}" data-i="${i}" data-f="unit" value="${escAttr(x.unit)}" placeholder="IU / mg"></td><td><input class="input" type="time" data-med="${kind}" data-i="${i}" data-f="time" value="${x.time}"></td><td><input class="check" type="checkbox" data-med="${kind}" data-i="${i}" data-f="administered" ${x.administered?"checked":""}></td><td><select class="select" data-med="${kind}" data-i="${i}" data-f="status">${STATUS_OPTIONS.map(s=>`<option ${x.status===s?"selected":""}>${s}</option>`).join("")}</select></td><td><input class="input" data-med="${kind}" data-i="${i}" data-f="notes" value="${escAttr(x.notes)}" placeholder="Reaction / pharmacy / notes"></td></tr>`).join("")}</tbody></table></div></div>`}
function monitoring(p){const sections=[[
"Stimulation Blood Monitoring",2,"stimulationBlood"],["Stimulation USG Monitoring",4,"stimulationUSG"],["Stimulation Doctor Visits","Track","stimulationVisits"],["FET Blood Monitoring",2,"fetBlood"],["FET USG Monitoring",5,"fetUSG"],["FET Doctor Visits","Track","fetVisits"]];return `<div class="card section"><div class="section-head"><div><h3>Monitoring & Visits</h3><div class="meta">The included quantities below follow the supplied package CSV.</div></div></div>${sections.map(([title,inc,key])=>{const a=p.monitoring[key]||[];return `<div style="margin-bottom:22px"><div class="section-head"><h3>${title}</h3><div class="meta">Included: ${inc} · Recorded: ${a.length}</div><button class="btn btn-secondary btn-sm" data-action="add-monitor" data-key="${key}">+ Add</button></div><div class="table-scroll"><table class="table"><thead><tr><th>Date</th><th>Result / Value</th><th>Status</th><th>Notes</th><th></th></tr></thead><tbody>${a.map((x,i)=>`<tr><td><input class="input" type="date" data-mon="${key}" data-i="${i}" data-f="date" value="${x.date||""}"></td><td><input class="input" data-mon="${key}" data-i="${i}" data-f="result" value="${escAttr(x.result||"")}" placeholder="E2 / LH / P4, follicle count, thickness…"></td><td><select class="select" data-mon="${key}" data-i="${i}" data-f="status">${STATUS_OPTIONS.map(s=>`<option ${x.status===s?"selected":""}>${s}</option>`).join("")}</select></td><td><input class="input" data-mon="${key}" data-i="${i}" data-f="notes" value="${escAttr(x.notes||"")}"></td><td><button class="btn btn-danger btn-sm" data-action="del-monitor" data-key="${key}" data-i="${i}">Remove</button></td></tr>`).join("")||`<tr><td colspan="5" class="empty">No entries recorded.</td></tr>`}</tbody></table></div></div>`}).join("")}</div>`}
function phaseChecklist(p,key){
 const ph=PHASE_TEMPLATE.find(x=>x.key===key),arr=p.phases?.[key]||[],s=phaseStats(arr);
 const row=(x,i)=>`<div class="check-row"><div class="check-main"><div class="check-title">${escHtml(x.item)}</div><div class="small">${escHtml(x.details)} — ${escHtml(x.included)}</div></div><input type="date" class="input compact" data-phase="${key}" data-i="${i}" data-f="plannedDate" value="${escAttr(x.plannedDate||"")}" title="Planned date"><select class="select status-select" data-phase="${key}" data-i="${i}" data-f="status">${STATUS_OPTIONS.map(v=>`<option ${x.status===v?"selected":""}>${v}</option>`).join("")}</select><input class="input notes-input" data-phase="${key}" data-i="${i}" data-f="notes" value="${escAttr(x.notes||"")}" placeholder="Notes"></div>`;
 return `<div class="card section"><div class="section-head"><div><h3>${ph.label} — Checklist</h3><div class="meta">${s.completed} of ${s.total} items completed · ${s.pct}%</div></div><div class="count-box"><b>${s.completed}/${s.total}</b><span>Completed</span></div></div><div class="checklist">${arr.map((x,i)=>row(x,i)).join("")}</div></div>`;
}
function retrieval(p){const r=p.retrieval;const fields=[["opuDate","OPU Date","date"],["eggsRetrieved","Eggs Retrieved","number"],["mii","MII","number"],["mi","MI","number"],["gv","GV","number"],["icsi","ICSI Count","number"],["fertilized","Fertilized","number"],["day3Embryos","Day 3 Embryos","number"],["blastocysts","Blastocysts","number"],["embryoGrades","Embryo Grades","text"],["anesthesia","Anesthesia / Sedation","text"],["otDaycare","OT & Day-Care","text"],["spermPrep","Sperm Prep","text"],["fertilization","ICSI / IVF Done","text"],["freshTransfer","Fresh Transfer","text"]];return `<div class="card section"><div class="section-head"><div><h3>Egg Retrieval & Embryology</h3><div class="meta">Capture the OPU, egg maturity and embryology outcomes requested in the reference.</div></div></div><div class="form-grid">${fields.map(([k,l,t])=>`<div class="field"><label>${l}</label><input class="input" type="${t}" data-record="retrieval" data-f="${k}" value="${escAttr(r[k]||"")}"></div>`).join("")}<div class="field full"><label>Clinical / Embryology Notes</label><textarea data-record="retrieval" data-f="notes">${escHtml(r.notes||"")}</textarea></div></div></div>`}
function freezing(p){const r=p.freezing;return `<div class="card section"><div class="section-head"><div><h3>Freezing & Storage</h3><div class="meta">Track applicability, freeze date and the approximate included storage period.</div></div><button class="btn btn-secondary btn-sm" data-action="calc-storage">Calculate +3 months</button></div><div class="form-grid">${[["embryoFrozen","Embryos Frozen","number"],["spermFrozen","Sperm Samples Frozen","number"],["oocyteFrozen","Oocytes Frozen","number"],["freezeDate","Freeze Date","date"],["storageEndDate","Free Storage End Date","date"]].map(([k,l,t])=>`<div class="field"><label>${l}</label><input class="input" type="${t}" data-record="freezing" data-f="${k}" value="${escAttr(r[k]||"")}"></div>`).join("")}<div class="field full"><label>Notes</label><textarea data-record="freezing" data-f="notes">${escHtml(r.notes||"")}</textarea></div></div></div>`}
function fet(p){const r=p.fet;return `<div class="card section"><div class="section-head"><div><h3>Frozen Embryo Transfer</h3><div class="meta">Track transfer readiness, endometrial thickness, embryos transferred and beta-hCG timing.</div></div></div><div class="form-grid">${[["transferDate","Transfer Date","date"],["endometrialThickness","Endometrial Thickness","text"],["embryosTransferred","Embryos Transferred","number"],["protocol","Protocol / Notes","text"],["betaHcgDate","Beta hCG Date","date"],["betaHcgResult","Beta hCG Result","text"]].map(([k,l,t])=>`<div class="field"><label>${l}</label><input class="input" type="${t}" data-record="fet" data-f="${k}" value="${escAttr(r[k]||"")}"></div>`).join("")}<div class="field full"><label>Transfer Notes</label><textarea data-record="fet" data-f="notes">${escHtml(r.notes||"")}</textarea></div></div></div>`}
function pregnancy(p){const r=p.pregnancy;return `<div class="card section"><div class="section-head"><div><h3>Pregnancy Confirmation</h3><div class="meta">Reference package includes Day 14 beta hCG, repeat quantitative test and 2 post-transfer consultations.</div></div></div><div class="form-grid">${[["testDate","Test Date","date"],["qualitative","Qualitative Beta hCG","text"],["quantitative","Quantitative / Repeat","text"],["consultation1","Post-Transfer Consultation 1","date"],["consultation2","Post-Transfer Consultation 2","date"]].map(([k,l,t])=>`<div class="field"><label>${l}</label><input class="input" type="${t}" data-record="pregnancy" data-f="${k}" value="${escAttr(r[k]||"")}"></div>`).join("")}<div class="field full"><label>Notes</label><textarea data-record="pregnancy" data-f="notes">${escHtml(r.notes||"")}</textarea></div></div></div>`}
function charges(p){const a=p.extraCharges||[];return `<div class="card section"><div class="section-head"><div><h3>Extra Charges</h3><div class="meta">Use this for items outside package inclusions or over the included quantity.</div></div><div class="count-box"><b>${fmtINR(extraTotal(p))}</b><span>Total Extra Charges</span></div></div><div class="charge-add"><input class="input" id="cdate" type="date"><input class="input" id="cdesc" placeholder="Description"><select class="select" id="ccat"><option value="">Category</option>${EXTRA_CHARGE_CATEGORIES.map(x=>`<option>${escHtml(x)}</option>`).join("")}</select><input class="input" id="camt" type="number" min="0" placeholder="Amount ₹"><input class="input" id="cnote" placeholder="Notes"><button class="btn btn-primary" data-action="add-charge">+ Add</button></div><div class="table-scroll"><table class="table"><thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Amount</th><th>Notes</th><th></th></tr></thead><tbody>${a.map((x,i)=>`<tr><td>${fmtDate(x.date)}</td><td>${escHtml(x.description)}</td><td>${escHtml(x.category)}</td><td>${fmtINR(x.amount)}</td><td>${escHtml(x.notes)}</td><td><button class="btn btn-danger btn-sm" data-action="del-charge" data-i="${i}">Remove</button></td></tr>`).join("")||`<tr><td colspan="6" class="empty">No extra charges.</td></tr>`}</tbody></table></div></div>`}
function notes(p){const a=(p.notes||[]).slice().reverse();return `<div class="card section"><div class="section-head"><div><h3>Notes & Timeline</h3><div class="meta">Record calls, patient concerns, doctor instructions, pharmacy notes or follow-ups.</div></div></div><textarea id="new-note" placeholder="Add a timeline note…"></textarea><button class="btn btn-primary" style="margin-top:8px" data-action="add-note">+ Add Note</button><div class="hr"></div><div class="timeline">${a.map(x=>`<div class="note"><b>${new Date(x.date).toLocaleString("en-IN")}</b><div>${escHtml(x.text)}</div></div>`).join("")||`<div class="empty">No notes yet.</div>`}</div></div>`}
function exportTab(p){return `<div class="card section"><div class="section-head"><div><h3>Export Data</h3><div class="meta">Download the current patient or the full tracker for reporting and backup.</div></div></div><div class="export-panel"><div class="export-box"><h4>This Patient — CSV</h4><p>One CSV containing patient info, programme items, daily medication, monitoring, procedures, billing and notes.</p><button class="btn btn-secondary" data-action="patient-csv">Download CSV</button></div><div class="export-box"><h4>This Patient — XLSX</h4><p>Multi-sheet workbook with separate tabs for each major area.</p><button class="btn btn-primary" data-action="patient-xlsx">Download XLSX</button></div><div class="export-box"><h4>All Patients — XLSX</h4><p>Summary, programme items, daily medication, monitoring, retrieval and charges for every patient.</p><button class="btn btn-secondary" data-action="export-all-xlsx">Download Full XLSX</button></div><div class="export-box"><h4>Browser Backup — JSON</h4><p>Full local data backup that can be retained securely alongside your reporting exports.</p><button class="btn btn-secondary" data-action="backup">Download JSON Backup</button></div></div></div>`}
function openModal(title,body){modal.innerHTML=`<div class="modal-back"><div class="modal"><div class="modal-head"><h3>${title}</h3><button class="close" data-action="close-modal">×</button></div><div class="modal-body">${body}</div></div></div>`}
function patientForm(p){
 const x=p||{},mat=(x.programType||"IVF")==="Maternity";
 const fields=[["name","Patient Name","text"],["uhid","UHID","text"],["age","Age","number"],["dob","Date of Birth","date"],["partner","Partner Name","text"],["contact","Primary Contact","tel"],["altContact","Alternate Contact","tel"],["doctor","Doctor","text"],["coordinator","Coordinator","text"],["cycleType","Cycle / Programme","text"],["diagnosis","Diagnosis","text"],["bloodGroup","Blood Group","text"],["emergencyContact","Emergency Contact","tel"]];
 return `<form id="patient-form"><div class="form-grid"><div class="field"><label>Patient Type</label><select class="select" name="programType"><option value="IVF" ${!mat?"selected":""}>IVF</option><option value="Maternity" ${mat?"selected":""}>Maternity</option></select></div>${fields.map(([k,l,t])=>`<div class="field"><label>${l}</label><input class="input" name="${k}" type="${t}" value="${escAttr(x[k]??"")}"></div>`).join("")}<div class="field"><label>${mat?"LMP (Last Menstrual Period)":"Package Start Date"}</label><input class="input" name="${mat?"lmp":"packageStartDate"}" type="date" value="${escAttr(x[mat?"lmp":"packageStartDate"]??"")}"></div><div class="field"><label>${mat?"Estimated Due Date":"Package Price (₹)"}</label><input class="input" name="${mat?"edd":"packagePrice"}" type="${mat?"date":"number"}" value="${escAttr(x[mat?"edd":"packagePrice"]??"")}"></div>${mat?`<div class="field"><label>Maternity Package</label><select class="select" name="maternityPackage"><option ${x.maternityPackage==="Full Maternity"||!x.maternityPackage?"selected":""}>Full Maternity</option><option ${x.maternityPackage==="Trimester-wise"?"selected":""}>Trimester-wise</option></select></div>`:""}<div class="field full"><label>Address</label><textarea name="address">${escHtml(x.address||"")}</textarea></div></div><div class="btn-group" style="justify-content:flex-end;margin-top:14px"><button type="button" class="btn btn-secondary" data-action="close-modal">Cancel</button><button class="btn btn-primary">${p?"Save Changes":"Create Patient"}</button></div></form>`;
}
function editPatient(p){
 openModal(p ? `Edit ${p.programType==="Maternity"?"Maternity":"IVF"} Patient` : "Add Patient",patientForm(p));
 document.getElementById("patient-form").onsubmit=e=>{
   e.preventDefault();const f=new FormData(e.target),o=Object.fromEntries(f.entries());
   if(!o.name.trim()){alert("Patient name is required.");return}
   if(p){Object.assign(p,o);p.age=Number(o.age)||"";if(o.programType==="Maternity"){p.packagePrice=Number(o.packagePrice)||0;if(!p.maternity)p.maternity=blankMaternityTrimesterRows();normalizeMaternityPatient(p)}else p.packagePrice=Number(o.packagePrice)||DEFAULT_PACKAGE_PRICE;p.updatedAt=new Date().toISOString()}
   else{state.patients.push(newPatient(o))}
   save().then(()=>{modal.innerHTML="";render()}).catch(e=>alert(e.message||"Could not save patient."))
 };
}
function autoDates(kind){const p=get(),arr=kind==="stimulation"?p.stimulationMedication:p.fetMedication;const start=p.packageStartDate;if(!start){alert("Add a package start date first.");return}arr.forEach((x,i)=>x.date=dateAdd(start,i));p.updatedAt=new Date().toISOString();save();render()}
function addMonitor(key){const p=get();p.monitoring[key].push({date:"",result:"",status:"Completed",notes:""});p.updatedAt=new Date().toISOString();save();render()}
document.addEventListener("submit",async e=>{
 if(e.target.id!=="login-form")return;
 e.preventDefault();
 const email=document.getElementById("login-email").value.trim(),password=document.getElementById("login-password").value;
 const err=document.getElementById("login-error");err.style.display="none";
 try{await signIn(email,password);state.user=await getCurrentUser();state.loading=true;render();state.patients=await loadPatients();state.loading=false;render()}
 catch(x){err.textContent=x.message||"Sign in failed.";err.style.display="block"}
});
document.addEventListener("click",async e=>{
 if(e.target.classList?.contains("modal-back")){modal.innerHTML="";return}
 const el=e.target.closest?.("[data-action]");if(!el)return;
 const action=el.dataset.action;
 switch(action){
  case"sign-out":try{await signOut();state.user=null;state.patients=[];state.view="dashboard";state.patientId=null;state.loading=false;render()}catch(x){alert(x.message||"Could not sign out.")}break;
  case"add":editPatient();break;
  case"edit":editPatient(get());break;
  case"open":{const id=el.dataset.id,p=get(id);if(!p){console.error("Patient not found:",id);return}state.view="patient";state.patientId=id;state.tab=(p.programType==="Maternity")?"maternity-overview":"overview";render();break;}
  case"back-dashboard":state.view="dashboard";state.patientId=null;render();break;
  case"type-filter":state.typeFilter=el.dataset.type;state.search="";render();break;
  case"close-modal":modal.innerHTML="";break;
  case"export-tab":if(state.patients.length){const list=state.typeFilter==="All"?state.patients:state.patients.filter(p=>(p.programType||"IVF")===state.typeFilter);if(list.length){state.view="patient";state.patientId=list[0].id;state.tab=(list[0].programType==="Maternity")?"export":"export";render()}else alert("No patients in this filter.")}else alert("Add a patient first.");break;
  case"export-summary-csv":{const list=state.typeFilter==="All"?state.patients:state.patients.filter(p=>(p.programType||"IVF")===state.typeFilter);exportSummaryCSV(list);break}
  case"export-summary-xlsx":{const list=state.typeFilter==="All"?state.patients:state.patients.filter(p=>(p.programType||"IVF")===state.typeFilter);exportSummaryXLSX(list);break}
  case"export-all-xlsx":exportAllXLSX(state.patients);break;
  case"patient-csv":exportPatientCSV(get());break;
  case"patient-xlsx":exportPatientXLSX(get());break;
  case"backup":exportBackupJSON(state.patients);break;
  case"auto-dates":autoDates(el.dataset.kind);break;
  case"add-monitor":addMonitor(el.dataset.key);break;
  case"del-monitor":{const p=get();p.monitoring[el.dataset.key].splice(+el.dataset.i,1);p.updatedAt=new Date().toISOString();save();render();break}
  case"add-charge":{const p=get(),d=document.getElementById("cdate")?.value||"",desc=document.getElementById("cdesc")?.value.trim()||"",cat=document.getElementById("ccat")?.value||"",amt=Number(document.getElementById("camt")?.value)||0,n=document.getElementById("cnote")?.value.trim()||"";if(!desc&&!amt){alert("Add a description or amount.");return}p.extraCharges.push({date:d,description:desc,category:cat,amount:amt,notes:n});p.updatedAt=new Date().toISOString();save();render();break}
  case"del-charge":{const p=get();p.extraCharges.splice(+el.dataset.i,1);p.updatedAt=new Date().toISOString();save();render();break}
  case"add-note":{const p=get(),t=document.getElementById("new-note")?.value.trim();if(!t)return;p.notes.push({date:new Date().toISOString(),text:t});p.updatedAt=new Date().toISOString();save();render();break}
  case"calc-storage":{const p=get();if(!p.freezing.freezeDate){alert("Enter the freeze date first.");return}p.freezing.storageEndDate=dateAdd(p.freezing.freezeDate,90);p.updatedAt=new Date().toISOString();save();render();break}
 }
});
document.addEventListener("input",e=>{
 if(e.target.id!=="search")return;
 state.search=e.target.value;
 const card=document.querySelector(".card.table-scroll");if(!card)return;
 const base=state.typeFilter==="All"?state.patients:state.patients.filter(p=>(p.programType||"IVF")===state.typeFilter);
 const q=state.search.toLowerCase().trim();
 const ps=q?base.filter(p=>[p.name,p.uhid,p.doctor,p.contact,p.partner].some(v=>String(v||"").toLowerCase().includes(q))):base;
 card.innerHTML=ps.length?patientsTable(ps):`<div class="empty"><strong>No matching patients</strong></div>`;
});
document.addEventListener("change",e=>{
 const el=e.target,p=get();if(!p)return;
 if(el.dataset.med){const a=el.dataset.med==="stimulation"?p.stimulationMedication:p.fetMedication,x=a[+el.dataset.i];x[el.dataset.f]=el.type==="checkbox"?el.checked:el.value;p.updatedAt=new Date().toISOString();save();return}
 if(el.dataset.mon){const x=p.monitoring[el.dataset.mon][+el.dataset.i];x[el.dataset.f]=el.value;p.updatedAt=new Date().toISOString();save();return}
 if(el.dataset.maternity){const x=p.maternity[el.dataset.maternity][+el.dataset.i];x[el.dataset.f]=el.value;p.updatedAt=new Date().toISOString();save();return}
 if(el.dataset.phase){const x=p.phases[el.dataset.phase][+el.dataset.i];x[el.dataset.f]=el.value;p.updatedAt=new Date().toISOString();save();return}
 if(el.dataset.record){p[el.dataset.record][el.dataset.f]=el.value;p.updatedAt=new Date().toISOString();save();return}
});

window.addEventListener("hashchange",()=>{const m=location.hash.match(/^#patient-tab-(.+)$/);if(!m)return;const p=get();if(!p)return;state.tab=m[1];render()});
