function dl(blob,name){const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),500)}
function esc(v){const s=v==null?"":String(v);return /[",\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}
function csv(rows){return rows.map(r=>r.map(esc).join(",")).join("\r\n")}
function safeName(n){return(n||"patient").replace(/[^a-z0-9]+/gi,"_").replace(/^_+|_+$/g,"")||"patient"}
function summaryRows(ps){const h=["Patient Name","UHID","Program Type","Age","Partner","Doctor","Coordinator","Contact","Cycle Type","Diagnosis","Package Start / LMP","Package Price","Current Stage","Completed Items","Total Items","Completion %","Extra Charges","Estimated Total"];const r=[h];ps.forEach(p=>{const s=programStats(p),e=extraTotal(p);r.push([p.name,p.uhid,p.programType||"IVF",p.age,p.partner,p.doctor,p.coordinator,p.contact,p.cycleType,p.diagnosis,(p.programType||"IVF")==="Maternity"?p.lmp:p.packageStartDate,p.packagePrice,currentProgramStage(p),s.completed,s.total,s.pct+"%",e,(Number(p.packagePrice)||0)+e])});return r}
function patientInfoRows(p){return [["Field","Value"],["Patient Name",p.name],["UHID",p.uhid],["Program Type",p.programType||"IVF"],["Age",p.age],["DOB",p.dob],["Partner",p.partner],["Contact",p.contact],["Alternate Contact",p.altContact],["Doctor",p.doctor],["Coordinator",p.coordinator],["Cycle Type",p.cycleType],["Diagnosis",p.diagnosis],["Blood Group",p.bloodGroup],["Emergency Contact",p.emergencyContact],["Address",p.address],["Package Start Date",p.packageStartDate],["Package Price (₹)",p.packagePrice],["Current Stage",currentProgramStage(p)],["Completion %",programStats(p).pct+"%"],["Extra Charges (₹)",extraTotal(p)]]}
function dailyRows(p,kind){const src=kind==="stimulation"?p.stimulationMedication:p.fetMedication;const h=["Patient","UHID","Course","Day","Date","Medication","Dose","Unit","Time","Administered","Status","Notes"];return [h,...src.map(x=>[p.name,p.uhid,kind==="stimulation"?"Stimulation":"FET",x.day,x.date,x.medication,x.dose,x.unit,x.time,x.administered?"Yes":"No",x.status,x.notes]) ]}
function monitoringRows(p){const h=["Patient","UHID","Phase","Type","Included","Date","Result / Value","Status","Notes"];const r=[h];const add=(phase,type,inc,a)=>a.forEach(x=>r.push([p.name,p.uhid,phase,type,inc,x.date||"",x.result||"",x.status||"Completed",x.notes||""]));add("Stimulation","Blood Test",2,p.monitoring.stimulationBlood||[]);add("Stimulation","USG Scan",4,p.monitoring.stimulationUSG||[]);add("Stimulation","Doctor Visit","Track",p.monitoring.stimulationVisits||[]);add("FET","Blood Test",2,p.monitoring.fetBlood||[]);add("FET","USG Scan",5,p.monitoring.fetUSG||[]);add("FET","Doctor Visit","Track",p.monitoring.fetVisits||[]);return r}
function phaseRows(p){const h=["Patient","UHID","Phase","Item","Details","Included","Planned Date","Actual Date","Status","Result / Value","Notes"];const r=[h];PHASE_TEMPLATE.forEach(ph=>(p.phases?.[ph.key]||[]).forEach(x=>r.push([p.name,p.uhid,ph.label,x.item,x.details,x.included,x.plannedDate,x.actualDate,x.status,x.result,x.notes])));return r}
function exportSummaryCSV(ps){dl(new Blob([csv(summaryRows(ps))],{type:"text/csv;charset=utf-8"}),"altius_patient_summary.csv")}
function exportSummaryXLSX(ps){const wb=XLSX.utils.book_new(),ws=XLSX.utils.aoa_to_sheet(summaryRows(ps));XLSX.utils.book_append_sheet(wb,ws,"Patient Summary");XLSX.writeFile(wb,"altius_patient_summary.xlsx")}
function maternityRows(p){
 const h=["Patient","UHID","Program Type","Trimester","Type","Test / Scan","Reference","Completed Date","Status","Notes"],r=[h];
 MATERNITY_TRIMESTERS.forEach(t=>(p.maternity?.[t.key]||[]).forEach(x=>r.push([p.name,p.uhid,"Maternity",t.label,x.type||"",x.item,x.included,x.completedDate||x.actualDate||"",x.status,x.notes||""])));
 return r;
}
function maternitySummaryRows(ps){
 const h=["Patient Name","UHID","Program Type","LMP","EDD","Current Trimester","T1 %","T2 %","T3 %","Overall %"],r=[h];
 ps.filter(p=>(p.programType||"IVF")==="Maternity").forEach(p=>{const a=MATERNITY_TRIMESTERS.map(t=>maternityStats(p,t.key).pct);r.push([p.name,p.uhid,"Maternity",p.lmp,p.edd,currentTrimester(p),a[0]+"%",a[1]+"%",a[2]+"%",maternityOverallStats(p).pct+"%"])});return r;
}
function exportAllXLSX(ps){const wb=XLSX.utils.book_new();[["Patient Summary",summaryRows(ps)]].forEach(([n,r])=>XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(r),n));let detail=[["Patient","UHID","Phase","Item","Details","Included","Planned Date","Actual Date","Status","Result","Notes"]];ps.forEach(p=>detail.push(...phaseRows(p).slice(1)));XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(detail),"Programme Items");let meds=[["Patient","UHID","Course","Day","Date","Medication","Dose","Unit","Time","Administered","Status","Notes"]];ps.forEach(p=>{meds.push(...dailyRows(p,"stimulation").slice(1),...dailyRows(p,"fet").slice(1))});XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(meds),"Daily Medication");let mon=[["Patient","UHID","Phase","Type","Included","Date","Result / Value","Status","Notes"]];ps.forEach(p=>mon.push(...monitoringRows(p).slice(1)));XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(mon),"Monitoring");
 let mat=[];ps.filter(p=>(p.programType||"IVF")==="Maternity").forEach(p=>mat.push(...maternityRows(p).slice(1)));if(mat.length)XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([maternityRows(ps.find(p=>(p.programType||"IVF")==="Maternity"))[0],...mat]),"Maternity Tracker");let ms=maternitySummaryRows(ps);if(ms.length>1)XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(ms),"Maternity Summary");let ret=[["Patient","UHID","OPU Date","Eggs Retrieved","MII","MI","GV","ICSI","Fertilized","Day 3 Embryos","Blastocysts","Embryo Grades","Anesthesia","OT/Daycare","Sperm Prep","Fertilization","Fresh Transfer","Notes"]];ps.forEach(p=>ret.push([p.name,p.uhid,p.retrieval.opuDate,p.retrieval.eggsRetrieved,p.retrieval.mii,p.retrieval.mi,p.retrieval.gv,p.retrieval.icsi,p.retrieval.fertilized,p.retrieval.day3Embryos,p.retrieval.blastocysts,p.retrieval.embryoGrades,p.retrieval.anesthesia,p.retrieval.otDaycare,p.retrieval.spermPrep,p.retrieval.fertilization,p.retrieval.freshTransfer,p.retrieval.notes]));XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(ret),"Retrieval & Embryology");let ch=[["Patient","UHID","Date","Description","Category","Amount","Notes"]];ps.forEach(p=>(p.extraCharges||[]).forEach(x=>ch.push([p.name,p.uhid,x.date,x.description,x.category,x.amount,x.notes])));XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(ch),"Extra Charges");XLSX.writeFile(wb,"altius_ivf_maternity_all_patients.xlsx")}
function exportPatientCSV(p){const rows=[...patientInfoRows(p),[],["PROGRAMME ITEMS"],...phaseRows(p),[],["STIMULATION DAILY MEDICATION"],...dailyRows(p,"stimulation"),[],["FET DAILY MEDICATION"],...dailyRows(p,"fet"),[],["MONITORING"],...monitoringRows(p),[],["RETRIEVAL & EMBRYOLOGY"],["Field","Value"],...Object.entries(p.retrieval||{}),[],["FREEZING"],["Field","Value"],...Object.entries(p.freezing||{}),[],["FET"],["Field","Value"],...Object.entries(p.fet||{}),[],["PREGNANCY"],["Field","Value"],...Object.entries(p.pregnancy||{}),[],["EXTRA CHARGES"],["Date","Description","Category","Amount","Notes"],...(p.extraCharges||[]).map(x=>[x.date,x.description,x.category,x.amount,x.notes]),[],["NOTES"],["Date","Note"],...(p.notes||[]).map(x=>[x.date,x.text]),...(((p.programType||"IVF")==="Maternity")?[[],["MATERNITY TRIMESTER TRACKER"],...maternityRows(p)]:[])];dl(new Blob([csv(rows)],{type:"text/csv;charset=utf-8"}),`altius_${(p.programType||"IVF").toLowerCase()}_${safeName(p.name)}.csv`)}
function exportPatientXLSX(p){const wb=XLSX.utils.book_new();const add=(name,rows)=>{const ws=XLSX.utils.aoa_to_sheet(rows);ws["!cols"]=rows[0]?.map(()=>({wch:22}))||[];XLSX.utils.book_append_sheet(wb,ws,name)};add("Patient Info",patientInfoRows(p));add("Programme",phaseRows(p));add("Stim Medication",dailyRows(p,"stimulation"));add("FET Medication",dailyRows(p,"fet"));add("Monitoring",monitoringRows(p));add("Retrieval",[["Field","Value"],...Object.entries(p.retrieval||{})]);add("Freezing",[["Field","Value"],...Object.entries(p.freezing||{})]);add("FET",[["Field","Value"],...Object.entries(p.fet||{})]);add("Pregnancy",[["Field","Value"],...Object.entries(p.pregnancy||{})]);add("Extra Charges",[["Date","Description","Category","Amount","Notes"],...(p.extraCharges||[]).map(x=>[x.date,x.description,x.category,x.amount,x.notes])]);add("Notes",[["Date","Note"],...(p.notes||[]).map(x=>[x.date,x.text])]);if((p.programType||"IVF")==="Maternity")add("Maternity Tracker",maternityRows(p));XLSX.writeFile(wb,`altius_${(p.programType||"IVF").toLowerCase()}_${safeName(p.name)}.xlsx`)}
function exportBackupJSON(ps){dl(new Blob([JSON.stringify(ps,null,2)],{type:"application/json"}),"altius_ivf_maternity_backup.json")}
